// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: calculator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalulatorServiceClient is the client API for CalulatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalulatorServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
}

type calulatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalulatorServiceClient(cc grpc.ClientConnInterface) CalulatorServiceClient {
	return &calulatorServiceClient{cc}
}

func (c *calulatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalulatorService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalulatorServiceServer is the server API for CalulatorService service.
// All implementations must embed UnimplementedCalulatorServiceServer
// for forward compatibility
type CalulatorServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	mustEmbedUnimplementedCalulatorServiceServer()
}

// UnimplementedCalulatorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCalulatorServiceServer struct {
}

func (UnimplementedCalulatorServiceServer) Sum(context.Context, *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedCalulatorServiceServer) mustEmbedUnimplementedCalulatorServiceServer() {}

// UnsafeCalulatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalulatorServiceServer will
// result in compilation errors.
type UnsafeCalulatorServiceServer interface {
	mustEmbedUnimplementedCalulatorServiceServer()
}

func RegisterCalulatorServiceServer(s grpc.ServiceRegistrar, srv CalulatorServiceServer) {
	s.RegisterService(&CalulatorService_ServiceDesc, srv)
}

func _CalulatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalulatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalulatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalulatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CalulatorService_ServiceDesc is the grpc.ServiceDesc for CalulatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalulatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalulatorService",
	HandlerType: (*CalulatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalulatorService_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculator.proto",
}
